image: renovate/renovate:25.47.2-slim

variables:
  LOG_LEVEL: info
  RENOVATE_AUTODISCOVER: 'true'
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_BINARY_SOURCE: docker
  RENOVATE_ENDPOINT: $CI_API_V4_URL
  RENOVATE_EXTENDS: 'github>whitesource/merge-confidence:beta'
  RENOVATE_IGNORE_PR_AUTHOR: 'true'
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  RENOVATE_ONBOARDING: 'true'
  RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
  RENOVATE_PLATFORM: gitlab
  RENOVATE_REPOSITORY_CACHE: 'true'
  RENOVATE_REQUIRE_CONFIG: 'true'

default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}-renovate
    paths:
      - $CI_PROJECT_DIR/renovate
  tags:
    - renovate
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - "$RENOVATE_LOG_FILE"

renovate:
  resource_group: renovate
  only:
    - schedules
  script:
    - renovate $RENOVATE_EXTRA_FLAGS

renovate:dry-run:
  except:
    - schedules
  script:
    - renovate --dry-run $RENOVATE_EXTRA_FLAGS

